version: "3"

services:
  serverless_node:
    # image: serverlesspolska/serverless-framework:v2.60
    image: amaysim/serverless:2.68.0
    container_name: serverless_node
    network_mode: host
    volumes:
      - ./:/app
    working_dir: /app
    env_file: .env
