service: router-pattern

provider:
  name: aws
  runtime: nodejs14.x
  stage: local # Update for other environment: dev, stg, prd
  region: ap-southeast-1
  environment:
    ENV: ${self:provider.stage}

custom:
  sqs-router: router-dlq
  sqs-service-a: service-a-dlq
  sqs-service-b: service-b-dlq
  sqs-service-c: service-c-dlq

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-lambda-dead-letter
  - serverless-offline

functions:
  router:
    handler: ./src/api/router.handler
    name: router
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: /{mode}
          method: GET
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource:
          - Fn::Join: [':', ['arn:aws:sqs', Ref: 'AWS::Region', Ref: 'AWS::AccountId', '${self:custom.sqs-router}']]
    deadLetter:
      sqs: ${self:custom.sqs-router}
  serviceA:
    handler: /src/services/service-a.handler
    name: service-a
    memorySize: 128 # mb
    timeout: 5 # seconds
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource:
          - Fn::Join: [':', ['arn:aws:sqs', Ref: 'AWS::Region', Ref: 'AWS::AccountId', '${self:custom.sqs-service-a}']]
    deadLetter:
      sqs: ${self:custom.sqs-service-a}
  serviceB:
    handler: /src/services/service-b.handler
    name: service-b
    memorySize: 128 # mb
    timeout: 5 # seconds
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource:
          - Fn::Join: [':', ['arn:aws:sqs', Ref: 'AWS::Region', Ref: 'AWS::AccountId', '${self:custom.sqs-service-b}']]
    deadLetter:
      sqs: ${self:custom.sqs-service-b}
  serviceC:
    handler: /src/services/service-c.handler
    name: service-c
    memorySize: 128 # mb
    timeout: 5 # seconds
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource:
          - Fn::Join: [':', ['arn:aws:sqs', Ref: 'AWS::Region', Ref: 'AWS::AccountId', '${self:custom.sqs-service-c}']]
    deadLetter:
      sqs: ${self:custom.sqs-service-c}
