service: router-pattern

provider:
  name: aws
  runtime: nodejs14.x
  stage: local # Update for other environment: dev, stg, prd
  region: ap-southeast-1
  environment:
    ENV: ${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline

functions:
  router:
    handler: ./src/api/router.handler
    name: router
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: /{mode}
          method: GET
  serviceA:
    handler: /src/services/service-a.handler
    name: service-a
    memorySize: 128 # mb
    timeout: 5 # seconds
  serviceA:
    handler: /src/services/service-b.handler
    name: service-b
    memorySize: 128 # mb
    timeout: 5 # seconds
