service: storage-first-pattern

provider:
  name: aws
  runtime: nodejs14.x
  stage: local # Update for other environment: dev, stg, prd
  region: ap-southeast-1
  environment:
    ENV: ${self:provider.stage}

custom:
  serverless-offline:
    resourceRoutes: true # HTTP proxy

plugins:
  apiGwSqs:
    apiEndpoint: !GetAtt
    queueName: !GetAtt ReceiverQ.Name

resources:
  Resources:
    ReceiverQ:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'receiver-q'

functions:
  getPost:
    handler: ./src/api/ack.acknowledge
    name: acknowledger
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - sqs:
          arn: !GetAtt ReceiverQ.Arn
